language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_APP