language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
  - yarn global add firebase-tools

after_success:
  - firebase deploy --project $FIREBASE_APP --non-interactive --token $FIREBASE_TOKEN