language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
after_success:
  - firebase use $FIREBASE_APP
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN