language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master